parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Birdperson\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Birdperson\Infrastructure\Handler\:
    resource: '../src/Infrastructure/Handler/*'
    tags: ['controller.service_arguments']

  Birdperson\Infrastructure\RayDonovanHandleOurErrorsInThisClass:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
