parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $tokenLifetime: 60
      $currentTime: ~
      $serverCount: 3
      $tokenUrl: 'https://host/app/%s'
      $secret: '%kernel.secret%'

  Birdperson\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Birdperson\Clock:
    public: true

  Birdperson\Infrastructure\Handler\:
    resource: '../src/Infrastructure/Handler/*'
    tags: ['controller.service_arguments']

  Birdperson\Infrastructure\RayDonovanHandleOurErrorsInThisClass:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
