parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  Birdperson\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  Birdperson\Handler\SendMeThatTastyToken:
    tags: ['controller.service_arguments']

  Birdperson\RayDonovanHandleOurErrorsInThisClass:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
